### ISSUE TITLE
Iteration 1 feedback

### ISSUE THREAD

**Issue by jbrucker** [oMojiko/ku-polls#31]
Nice work on iteration 1.  But 3 minor problems and one more severe one:
1. No requirements.txt
2. A country has only 1 capital city, so the question should be "What is the capital city of Australia?" (not "a capital")
3. "iteration1" branch is named "Iteration1"

the more severe problem:
- unit tests pass on 'main', but 4 tests fail when run on 'Iteration1'.

**Comment by SeventwoZ** [comment]
- [x]  Added requirements.txt
- [x]  Changing a question text
- [x]  Rename a branch
- [x]  Fixing a unittest

**Comment by SeventwoZ** [comment]
Finished
